name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Composer packages
        run: composer install --working-dir=tools --prefer-dist --no-progress

      - name: Run PHP CS fixer
        run: tools/vendor/bin/php-cs-fixer check

  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Composer packages
        run: composer install --prefer-dist --no-progress

      - name: Install Composer packages for tools
        run: composer install --working-dir=tools --prefer-dist --no-progress

      - name: Run PHPStan
        run: tools/vendor/bin/phpstan analyse

  phpunit:
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: '5.6'
            phpunit-config: 'phpunit-5.dist.xml'
          - php-version: '7.0'
            phpunit-config: 'phpunit-5.dist.xml'
          - php-version: '7.1'
            phpunit-config: 'phpunit-5.dist.xml'
          - php-version: '7.2'
            phpunit-config: 'phpunit-5.dist.xml'
          - php-version: '7.3'
            phpunit-config: 'phpunit-9.dist.xml'
          - php-version: '7.4'
            phpunit-config: 'phpunit-9.dist.xml'
          - php-version: '8.0'
            phpunit-config: 'phpunit-9.dist.xml'
          - php-version: '8.1'
            phpunit-config: 'phpunit-10.dist.xml'
          - php-version: '8.2'
            phpunit-config: 'phpunit-11.dist.xml'
          - php-version: '8.3'
            phpunit-config: 'phpunit-11.dist.xml'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Validate composer.json file
        run: composer validate --strict

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php-version }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php-version }}-composer-

      - name: Install Composer packages
        run: composer install --prefer-dist --no-progress

      - name: Run PHPUnit
        run: vendor/bin/phpunit -c ${{ matrix.phpunit-config }}

  phpunit-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: pcov

      - name: Install Composer packages
        run: composer install --prefer-dist --no-progress

      - name: Run PHPUnit
        run: vendor/bin/phpunit -c phpunit-11.dist.xml --coverage-clover coverage.xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
